from keyboards.general_kb import kb_general
from keyboards.authors_kb import kb_authors
from keyboards import keyboards_text
from keyboards.book_author_kb import kb_book_author
from keyboards.books_kb import kb_books
from keyboards.book_genre_kb import kb_book_genre
from keyboards.borrows_kb import kb_borrows
from keyboards.genres_kb import kb_genres
from keyboards.users_kb import kb_users
